config/routes.rb
Rails.application.routes.draw do
  resources :avatars
  resources :messages
  resources :chat_rooms, only: [:new, :create, :show, :index]
  get '/game', :controller => 'games', :action => 'game'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  root to: "chat_rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :avatars, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :set_avatar, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:create]


  # GET /avatars
  # GET /avatars.json
  def index
    @avatars = Avatar.all
  end

  # GET /avatars/1
  # GET /avatars/1.json
  def show
  end

  # GET /avatars/new
  def new
    @avatar = Avatar.new
  end

  # GET /avatars/1/edit
  def edit
  end

  # POST /avatars
  # POST /avatars.json
  def create
    p "mah params" + params.to_s
    p request.body.read
     data = JSON.parse(request.body.read)
    p "mah data" + data.to_s
   
    params = data["avatar"]
    params[:name] = current_user.name
    p params
    @avatar = current_user.avatars.build(params)

    if @avatar.save
      p "Success!"
      @avatar.id.to_json
    end
  end

  # PATCH/PUT /avatars/1
  # PATCH/PUT /avatars/1.json
  def update
    respond_to do |format|
      if @avatar.update(avatar_params)
        format.html { redirect_to @avatar, notice: 'Avatar was successfully updated.' }
        format.json { render :show, status: :ok, location: @avatar }
      else
        format.html { render :edit }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avatars/1
  # DELETE /avatars/1.json
  def destroy
    @avatar.destroy
    respond_to do |format|
      format.html { redirect_to avatars_url, notice: 'Avatar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avatar
      @avatar = Avatar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avatar_params
      params.require(:avatar).permit(:xPos, :yPos)
    end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:show, :edit, :destroy]
  before_action :message, only: [:show]
  # GET /chat_rooms
  # GET /chat_rooms.json
  def index
    @chat_rooms = ChatRoom.all
  end

  # GET /chat_rooms/1
  # GET /chat_rooms/1.json
  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
  end

  # GET /chat_rooms/new
  def new
    @chat_room = ChatRoom.new
  end

  # GET /chat_rooms/1/edit
  def edit
  end

  # POST /chat_rooms
  # POST /chat_rooms.json
  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)

    respond_to do |format|
      if @chat_room.save
        format.html { redirect_to chat_rooms_path, notice: 'Chat room was successfully created.' }
        format.json { render :show, status: :created, location: @chat_room }
      else
        format.html { render :new }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_rooms/1
  # PATCH/PUT /chat_rooms/1.json


  # DELETE /chat_rooms/1
  # DELETE /chat_rooms/1.json
  def destroy
    @chat_room.destroy
    respond_to do |format|
      format.html { redirect_to chat_rooms_url, notice: 'Chat room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_room
      @chat_room = ChatRoom.find(params[:id])
    end

    def message
      @message = Message.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_room_params
      params.require(:chat_room).permit(:title)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def game
  	# Game.delete_all
  	# Game.create
  	

    if !current_user.avatars[0]	
    	@avatar = current_user.avatars.build(xPos: 500, yPos: 500, name: current_user.name)
    	@avatar.save
    end
    @avatar = current_user.avatars[0]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all
  end

  def show
  end

  def new
    @message = Message.new
  end

  def edit
  end

  def create
    @message = current_user.messages.build(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to request.referrer, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:body, :chat_room_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/avatars/_form.html.erb
<%= form_with(model: avatar, local: true) do |form| %>
  <% if avatar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(avatar.errors.count, "error") %> prohibited this avatar from being saved:</h2>

      <ul>
      <% avatar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :avatar_user_id %>
  </div>

  <div class="field">
    <%= form.label :xPos %>
    <%= form.number_field :xPos, id: :avatar_xPos %>
  </div>

  <div class="field">
    <%= form.label :yPos %>
    <%= form.number_field :yPos, id: :avatar_yPos %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :avatar_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/avatars/edit.html.erb
<h1>Editing Avatar</h1>

<%= render 'form', avatar: @avatar %>

<%= link_to 'Show', @avatar %> |
<%= link_to 'Back', avatars_path %>

app/views/avatars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Avatars</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Xpos</th>
      <th>Ypos</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avatars.each do |avatar| %>
      <tr>
        <td><%= avatar.user %></td>
        <td><%= avatar.xPos %></td>
        <td><%= avatar.yPos %></td>
        <td><%= avatar.name %></td>
        <td><%= link_to 'Show', avatar %></td>
        <td><%= link_to 'Edit', edit_avatar_path(avatar) %></td>
        <td><%= link_to 'Destroy', avatar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avatar', new_avatar_path %>

app/views/avatars/new.html.erb
<h1>New Avatar</h1>

<%= render 'form', avatar: @avatar %>

<%= link_to 'Back', avatars_path %>

app/views/avatars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @avatar.user %>
</p>

<p>
  <strong>Xpos:</strong>
  <%= @avatar.xPos %>
</p>

<p>
  <strong>Ypos:</strong>
  <%= @avatar.yPos %>
</p>

<p>
  <strong>Name:</strong>
  <%= @avatar.name %>
</p>

<%= link_to 'Edit', edit_avatar_path(@avatar) %> |
<%= link_to 'Back', avatars_path %>

app/views/chat_rooms/_form.html.erb
<%= form_with(model: chat_room, local: true) do |form| %>
  <% if chat_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat_room.errors.count, "error") %> prohibited this chat_room from being saved:</h2>

      <ul>
      <% chat_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :chat_room_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chat_rooms/edit.html.erb
<h1>Editing Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Enter', @chat_room %> |
<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chat Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chat_rooms.each do |chat_room| %>
      <tr>
        <td><%= chat_room.title %></td>
        <td><%= chat_room.user %></td>
        <td><%= link_to 'Enter', chat_room %></td>
        <td><%= link_to 'Delete', chat_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat Room', new_chat_room_path %>

app/views/chat_rooms/new.html.erb
<h1>New Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chat_room.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @chat_room.user %>
</p>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>

<%= render 'messages/form', message: @message %>

<%= link_to 'Back', chat_rooms_path %>

app/views/games/game.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <script> playerAvatar = new Avatar(<%=@avatar.xPos %>,<%=@avatar.yPos%>,"<%= @avatar.name%>", <%= @avatar.id %>, 40) </script>

  </head>
  <body>
    <canvas id="game-board-canvas" width="1200" height="600" style="background-color:#e9e9e0">
      Game requires HTML5 support. Sorry.
    </canvas>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mmog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </header>

    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |form| %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :message_body %>
  </div>

  <div class="actions">
    <%= hidden_field_tag 'message[chat_room_id]', @chat_room.id %>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="message">
  <%= message.user.name %> at <%= message.timestamp %> says</span><br>
  <%= message.body %>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Chat room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= message.user %></td>
        <td><%= message.chat_room %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<p>
  <strong>Chat room:</strong>
  <%= @message.chat_room %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>